# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f06956ce2b8974ac26f2d35d1ef1dff280831f487a96fdf40678a045b3c326b2af3c18f324ee699a66ed3b3d9b6d9a8a485cb4e536531a622a6afa934787cf59

test:
  secret_key_base: 7aa6b9026e7b062f69eb937941788422d871430a987f067f4f98e2dc927218e604f5232f50b7b262d1183d47e83d4db3dda3e24d4c95f6aaf527d73d58862ada

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
